name: Protect opendbc_repo on Gusdaz-SSH

on:
  pull_request:
    branches: [Gusdaz-SSH]

jobs:
  guard:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check for changes in opendbc_repo
        run: |
          echo "Checking for changes in opendbc_repo directory..."

          # Get the base branch for comparison
          git fetch origin ${{ github.base_ref }}

          # Check for changed files in opendbc_repo
          CHANGED_FILES=$(git diff --name-only \
            origin/${{ github.base_ref }}...HEAD -- opendbc_repo/)

          if [ -n "$CHANGED_FILES" ]; then
            echo "❌ ERROR: Changes detected in opendbc_repo directory!"
            echo ""
            echo "The following files in opendbc_repo were modified:"
            echo "$CHANGED_FILES"
            echo ""
            echo "Files in opendbc_repo are protected and cannot be"
            echo "modified via pull requests to Gusdaz-SSH."
            echo "Please remove these changes from your pull request."
            exit 1
          else
            echo "✅ No changes detected in opendbc_repo directory."
            echo "Check passed!"
          fi
